"""empty message

Revision ID: adf0cefdc42d
Revises: de515918b270
Create Date: 2018-10-24 10:27:20.711483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adf0cefdc42d'
down_revision = 'de515918b270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmpassword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmpassword', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
