"""empty message

Revision ID: de515918b270
Revises: aac5ab85095a
Create Date: 2018-10-24 10:21:55.653408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de515918b270'
down_revision = 'aac5ab85095a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmpassword', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmpassword')
    # ### end Alembic commands ###
