"""empty message

Revision ID: fd8b91ffdbe2
Revises: 31983f1c919c
Create Date: 2018-10-24 20:51:46.848321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8b91ffdbe2'
down_revision = '31983f1c919c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('question_ibfk_1', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['author_id'], ['id'])
    op.drop_column('question', 'auther_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('auther_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_ibfk_1', 'question', 'user', ['auther_id'], ['id'])
    op.drop_column('question', 'author_id')
    # ### end Alembic commands ###
